name: auto_orientation
description: Set the device orientation programmatically for iOS and Android
version: 2.3.0
homepage: https://github.com/bytepark/auto_orientation

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.12.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: de.bytepark.autoorientation
        pluginClass: AutoOrientationPlugin
      ios:
        pluginClass: AutoOrientationPlugin
